name: Verify NPM

on:
  push:
    branches:
      - ci-debug

jobs:
  validate-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: npm config list -l
      - run: printenv
      - name: Ensure access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
